### ISSUE TITLE
cannot stat 'bib_tui.awk'

### ISSUE THREAD

**Issue by aravinat21** [huijunchen9260/bib.awk#2]
`$ make install` fails with the subjected error.

```sh
[aravinat21@aravinat21 ~src/bib.awk]$ make install
cp: cannot stat 'bib_tui.awk': No such file or directory
make: *** [Makefile:9: install] Error 1

```

**Comment by huijunchen9260** [comment]
Supposed to be fixed by f58da52421312c2da83f1103801557943bb88b6d. If there's any question, feel free to contact me through this issue!
