### ISSUE TITLE
Menu selection not working?

### ISSUE THREAD

**Issue by kbcb** [huijunchen9260/bib.awk#3]
Hello,

I'm very keen to try your awk application. Unfortunately it does not seem to respond to any menu selection. I tried on FreeBSD 13.1/13.2, Ubuntu Server 22 and OpenBSD 7.3 to no avail. May you please have a look or point me in the right direction to try and fix it myself? Many thanks!

**Comment by huijunchen9260** [comment]
Could you elaborate on what's happening? 

If possible, a recording through [asciinema](https://asciinema.org/) would be highly appreciated.

**Comment by kbcb** [comment]
Hello Chen,

here is the requested link:

https://asciinema.org/a/9HoCKA5ec7hUjRyG7EqXPVt3T

You will see ... nothing .. because whenever I type a number and hit enter only a zero appears on top. Nothing else... :-( 

Many thanks again.

**Comment by huijunchen9260** [comment]
May I ask if are you using Linux/macOS on your personal computer? Since this is a situation that happens on the server, I also encountered some similar situations when I use my [fm.awk](https://github.com/huijunchen9260/fm.awk) project on computing clusters. Would you mind downloading the bib.awk on your Linux/macOS laptop (if you are using it) and test whether the menu selection is working?

**Comment by kbcb** [comment]
Hello,
on my M1 MacBook Air it's the exact same situation :-(
Best regards and many thanks.

**Comment by huijunchen9260** [comment]
I just git cloned this repo to the cluster and the menu selection is working 🤔🤔

What version/variety of awk are you using? Right now this program has been tested in gawk and mawk.
In the recording, when you press `j` key, does the selected item goes down? Or it is just not moving until you hit a number?

**Comment by kbcb** [comment]
> I just git cloned this repo to the cluster and the menu selection is working
 🤔🤔
I am sorry. I have to choose a selection with the 'right'-key (mapped to 'l').
Return/Enter/Space do not work for selection ... Perhaps you want to adjust your manual on that to avoid these kind of stupid requests? (Just l - right/choose or similar?)
Indeed it is working in OpenBSD 7.3, gawk 5.1.
Many thanks for your time and help.

**Comment by huijunchen9260** [comment]
Thanks! I will close issue with update https://github.com/huijunchen9260/bib.awk/commit/cf08d98a9e4a54e99255087749a9760731b0f791

**Comment by huijunchen9260** [comment]
Also I added the right arrow which is missing before with this update: 
https://github.com/huijunchen9260/bib.awk/commit/6a7e8a1c80c6ae34302641d641624401c0b11861
